# Generated by Django 5.0 on 2023-12-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='btc_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USDT_ERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='usdt_erc20_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USDT_TRC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='usdt_trc20_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
        ),
    ]
