# Generated by Django 5.0 on 2023-12-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btc',
            options={'verbose_name': 'BTC', 'verbose_name_plural': 'BTC'},
        ),
        migrations.AlterModelOptions(
            name='usdt_erc20',
            options={'verbose_name': 'USDT ERC20', 'verbose_name_plural': 'USDT ERC20'},
        ),
        migrations.AlterModelOptions(
            name='usdt_trc20',
            options={'verbose_name': 'USDT TRC20', 'verbose_name_plural': 'USDT TRC20'},
        ),
    ]
